name: AlSaqr
description: "AlSaqr"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.4+11

environment:
   sdk: '>=3.4.1 <4.0.0'
   

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  file_picker: ^10.3.7
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  dropdown_search: ^5.0.6
  flutter_settings_ui: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  google_maps_flutter: ^2.7.0
  location: ^8.0.1
  flutter_pdfview: ^1.3.2
  get: ^4.6.6
  connectivity_plus: ^7.0.0
  syncfusion_flutter_pdfviewer: ^30.2.7
  path_provider: ^2.1.5
  device_info_plus: ^11.5.0
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.1
  animate_do: ^4.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  multi_dropdown: ^3.0.1
  change_app_package_name: ^1.5.0
  unique_identifier: ^0.4.0
  mime: ^2.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  flutter_file_dialog: ^3.0.2
  open_filex: ^4.7.0
  device_preview: ^1.3.1
  http: ^1.6.0

    
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^6.0.0

flutter_launcher_icons:  
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/alsaqrlogo.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/alsaqrlogo.jpeg"
  
flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/

